spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mariadb://127.0.0.1:3306/groundhog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false